name: musio
description: "LKM Player - Lecteur audio Flutter avancé avec support des métadonnées et paroles"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # Audio
  just_audio: ^0.9.36
  audio_service: ^0.18.12
  on_audio_query: ^2.9.0
  audiotagger: ^2.2.1
  rxdart: ^0.27.7
  
  # Data Models
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  
  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.3 # Pour les paramètres
  
  # UI
  flutter_animate: ^4.5.0
  flutter_lyric: ^2.0.4+6
  palette_generator: ^0.3.3+3
  
  # Navigation
  go_router: ^14.0.2
  
  # Utils
  http: ^1.2.0
  logger: ^2.4.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  path: ^1.9.1
  uuid: ^4.5.2
  share_plus: ^7.2.2
  package_info_plus: ^8.0.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.11
  
  # Icon Generation
  flutter_launcher_icons: ^0.13.1

  # Hive
  hive_generator: ^2.0.1
  
  # Linting
  flutter_lints: ^3.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # optional

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon/
